parameters:
    app.listener.comment.class: AppBundle\EventListener\CommentCreatedListener

services:
    app.listener.comment:
        class: %app.listener.comment.class%
        arguments: ["@session"]
        tags:
            -  { name: kernel.event_subscriber }
